angelhack13/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.simple import direct_to_template
from stack.views import LandingPageView, CompanyPageView, SearchListView
from django.contrib.auth import views as auth_views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

	# registration complete
	url(r'^register/complete/$',
	   direct_to_template,
	   {'template': 'registration/registration_complete.html'},
	   name='registration_complete'),

    # Examples:
    url(r'^register/', 'users.views.register', name='register'),

    # login
        url(r'^login/$', 'users.views.login', name='login'),
                
    # logout
        url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),

    # registration complete
    url(r'^register/complete/$',
           direct_to_template,
           {'template': 'registration/registration_complete.html'},
           name='registration_complete'),

        url(r'^activate/complete/$',
        direct_to_template,
        {'template': 'registration/activation_complete.html'},
        name='seller_registration_activation_complete'),

    #custom view for activation completion to display right login page (seller vs buyer)
    url(r'^activate/complete/$',
                           'users.views.activation_complete',
                           name='registration_activation_complete'),

    (r'', include('registration.backends.default.urls')),

    url(r'^$', LandingPageView.as_view(), name='landing_page'),

    url(r'^search/', SearchListView.as_view(), name='search'),

    url(r'^company/(?P<company_slug>[\w-]+)/$', CompanyPageView.as_view(), name='company_page'),
    url(r'^newstack/$', 'stack.views.CreateStackForm', name='new_stack'),
    # url(r'^angelhack13/', include('angelhack13.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^admin/', include(admin.site.urls)),
#    url(r'^submit/(?P<component>\d)/$', 'stack.views.submit'),
)

stack/models.py
from django.db import models
from django.db.models.signals import post_init, pre_init, post_save, pre_save
from django.template.defaultfilters import slugify
from django.dispatch import receiver

# Create your models here.

class ComponentList(models.Model):
	component_name = models.CharField(max_length=64, null=True, default=None, blank=True)

class StackItem(models.Model):
	item_tag = models.CharField(max_length=64, null=True, default=None, blank=True)
	item_type = models.CharField(max_length=64, null=True, default=None, blank=True)
	item_component = models.ForeignKey(ComponentList, null=True, blank=True, default=None)
	item_justification = models.CharField(max_length=1024, null=True, default=None, blank=True)

def extract_tags(s):
	return s.split(' ')

class TechStack(models.Model):
	domain = models.CharField(max_length=128, null=True, default=None, blank=True)
	company_slug = models.SlugField(max_length=255, unique=True)

	company_name = models.CharField(max_length=200, blank = True, null = True, verbose_name='Company Name')
	company_description = models.CharField(max_length=1000, blank = True, null = True, verbose_name='Company Description')
	company_type_of_application = models.CharField(max_length=1000, blank = True, null = True, verbose_name='Type of application')

	frontend_languages = models.CharField(max_length=200, blank = True, null = True, verbose_name='Languages')
	frontend_framework = models.CharField(max_length=200, blank = True, null = True, verbose_name='Framework')
	frontend_libraries = models.CharField(max_length=200, blank = True, null = True, verbose_name='Libraries')
	frontend_description = models.CharField(max_length=1000, blank = True, null = True,verbose_name='Why did you use these?')

	backend_languages = models.CharField(max_length=200, blank = True, null = True, verbose_name='Languages')
	backend_framework = models.CharField(max_length=200, blank = True, null = True, verbose_name='Framework')
	backend_libraries = models.CharField(max_length=200, blank = True, null = True, verbose_name='Libraries')
	backend_description = models.CharField(max_length=1000, blank = True, null = True, verbose_name='Why did you use these?')

	database = models.CharField(max_length=200, blank = True, null = True, verbose_name='Databases')
	database_description = models.CharField(max_length=1000, blank = True, null = True, verbose_name='Why did you use these?')

	server_os = models.CharField(max_length=200, blank = True, null = True, verbose_name='OS')
	server_configuration = models.CharField(max_length=200, blank = True, null = True, verbose_name='Configuration')
	server_ram = models.CharField(max_length=200, blank = True, null = True, verbose_name='RAM')
	server_nodes = models.CharField(max_length=200, blank = True, null = True, verbose_name='#Nodes')
	server_hosting_provider = models.CharField(max_length=200, blank = True, null = True, verbose_name='Hosting Provider')
	server_description = models.CharField(max_length=1000, blank = True, null = True, verbose_name='Why did you use these?')
	#connection to kiran's model

	@property
	def get_contributors(self):
		l=[]
		for c in self.contributors.all():
			l.append(c.get_name)
		return 

	@property
	def get_domain(self):
		return self.domain
	
	@property
	def get_company_description(self):
		return self.company_description

	@property
	def get_company_types(self):
		return extract_tags(self.company_type_of_application)

	@property
	def get_company_name(self):
		return self.company_name

	@property
	def get_company_slug(self):
		return self.company_slug
	
	@property
	def get_frontend_languages(self):
		return extract_tags(self.frontend_languages)

	@property
	def get_frontend_framework(self):
		return extract_tags(self.frontend_framework)

	@property
	def get_frontend_libraries(self):
		return extract_tags(self.frontend_libraries)
		
	@property
	def get_backend_languages(self):
		return extract_tags(self.backend_languages)

	@property
	def get_backend_framework(self):
		return extract_tags(self.backend_framework)

	@property
	def get_backend_libraries(self):
		return extract_tags(self.backend_libraries)

	@property
	def get_databases(self):
		return extract_tags(self.database)

	@property
	def get_server_configuration(self):
		return extract_tags(self.server_configuration)

	@property
	def get_server_ram(self):
		return self.server_ram

	@property
	def get_server_nodes(self):
		return self.server_nodes

	@property
	def get_server_hosting_provider(self):
		return extract_tags(self.server_hosting_provider)

	@property
	def get_server_description(self):
		return self.server_description

	@property
	def get_summary_tags(self):
		a=self.get_company_types
		a.extend(self.get_backend_languages)
		a.extend(self.get_backend_framework)
		a.extend(self.get_server_hosting_provider)
		return a

	@classmethod
	def get_featured_list(cls):
		return TechStack.objects.all()[:10]

@receiver(post_save, sender=TechStack)
def slugify_company_name(sender,instance,created,**kwargs):
    if created:
        instance.company_slug =  slugify(instance.company_name)
        instance.save()

stack/forms.py
from django.forms.models import inlineformset_factory
from stack.models import StackItem, TechStack, ComponentList
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django import forms
'''
def FrontendFormsetHelper(domain=None):
	if domain is not None:
		StackItemFormset =  inlineformset_factory(ComponentList, StackItem, max_num=3, extra=3)
		try:
			req_stack = TechStack.objects.get(domain=domain)
			req_component = ComponentList.objects.get(component_name="Frontend")
			formset = StackItemFormset(instance=req_component, queryset = StackItem.objects.filter(tech_stack = req_stack))
			return formset
		except ObjectDoesNotExist:
			req_component = ComponentList.objects.get(component_name="Frontend")
			formset = StackItemFormset(queryset = StackItem.objects.none(), initial=[
				{'item_type':'Language', },
				{'item_type':'Framework', },
				{'item_type':'Library', }
				])
			return formset

def BackendFormsetHelper(domain=None):
	if domain is not None:
		StackItemFormset =  inlineformset_factory(ComponentList, StackItem, max_num=3, extra=3)
		try:
			req_stack = TechStack.objects.get(domain=domain)
			req_component = ComponentList.objects.get(component_name="Backend")
			formset = StackItemFormset(instance=req_component, queryset = StackItem.objects.filter(tech_stack = req_stack))
			return formset
		except ObjectDoesNotExist:
			req_component = ComponentList.objects.get(component_name="Backend")
			formset = StackItemFormset(queryset = StackItem.objects.none(), initial=[
				{'item_type':'Language', },
				{'item_type':'Framework', },
				{'item_type':'Library', }
				])
			return formset

def ServerFormsetHelper(domain=None):
	if domain is not None:
		StackItemFormset =  inlineformset_factory(ComponentList, StackItem, max_num=3, extra=3)
		try:
			req_stack = TechStack.objects.get(domain=domain)
			req_component = ComponentList.objects.get(component_name="Server")
			formset = StackItemFormset(instance=req_component, queryset = StackItem.objects.filter(tech_stack = req_stack))
			return formset
		except ObjectDoesNotExist:
			req_component = ComponentList.objects.get(component_name="Server")
			formset = StackItemFormset(queryset = StackItem.objects.none(), initial=[
				{'item_type':'OS', },
				{'item_type':'Configuration', },
				{'item_type':'Hosting', }
				])
			return formset

def DatabaseFormsetHelper(domain=None):
	if domain is not None:
		StackItemFormset =  inlineformset_factory(ComponentList, StackItem, max_num=3, extra=3)
		try:
			req_stack = TechStack.objects.get(domain=domain)
			req_component = ComponentList.objects.get(component_name="Database")
			formset = StackItemFormset(instance=req_component, queryset = StackItem.objects.filter(tech_stack = req_stack))
			return formset
		except ObjectDoesNotExist:
			req_component = ComponentList.objects.get(component_name="Database")
			formset = StackItemFormset(queryset = StackItem.objects.none())
			return formset
'''

class TechStackForm(forms.ModelForm):    
    class Meta:
        model = TechStack
        exclude = ('domain', 'stack_item', 'company_slug' )

users/forms.py
from emailusernames.forms import EmailAuthenticationForm, EmailUserCreationForm
from django.contrib.auth.models import User
from django import forms

class HackerRegistrationForm(EmailUserCreationForm):
    """
    Email Registration Form

    This is a custom Email Registration form that inherits EmailUserCreationForm from
    emailusernames to make it compatible with django-registration

    See https://github.com/dabapps/django-email-as-username/issues/17

    Since django-registration's register view expects a username argument, we pass it in here
    
    """
    first_name = forms.CharField()
    last_name = forms.CharField()
    position = forms.CharField()

    def __init__(self, *args, **kwargs):
        super(HackerRegistrationForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = ['first_name', 'last_name', 'position', 'email', 'password1', 'password2']
    
    def clean_email(self):
        """
        Check the supplied email address against a list of known free
        webmail domains.
        
        """    	
    	bad_domains = ['aim.com', 'aol.com', 'email.com', 'gmail.com',
                   'googlemail.com', 'hotmail.com', 'hushmail.com',
                   'msn.com', 'mail.ru', 'mailinator.com', 'live.com',
                   'yahoo.com']

        email_domain = self.cleaned_data['email'].split('@')[1]
        
        if email_domain in bad_domains:
            raise forms.ValidationError(("Please sign up with your company email address."))

        email = self.cleaned_data["email"]
        from emailusernames.utils import user_exists
        if user_exists(email):
            raise forms.ValidationError(("A user with that email already exists."))

        return self.cleaned_data['email']

    def clean(self):
        cleaned_data = super(HackerRegistrationForm, self).clean()
        if cleaned_data.has_key('email'):
            cleaned_data['username'] = cleaned_data['email']
        return cleaned_data

stack/views.py
# Create your views here.
from django.views.generic import ListView, DetailView, TemplateView
from django.forms.models import inlineformset_factory
from stack.models import StackItem, TechStack, ComponentList
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.shortcuts import render_to_response
from django.http import HttpResponse
from django.core.context_processors import csrf
from stack.forms import TechStackForm
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.views.generic import ListView, DetailView, TemplateView

class LandingPageView(TemplateView):
	template_name = "landing.html"
	
	def get_context_data(self, **kwargs):
		context = super(LandingPageView, self).get_context_data(**kwargs)
		context['featured_list']=TechStack.get_featured_list()
 		return context

class CompanyPageView(DetailView):
    template_name = "company.html"
    model = TechStack
    context_object_name = 'stack'

    def get_object(self):
        # Call the superclass
        company_slug = self.kwargs['company_slug']
        object = get_object_or_404(TechStack, company_slug=company_slug)
        #object = TechStack.objects.get(id=1)

        return object

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(CompanyPageView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['company_name'] = self.object.company_name
        context['company_description'] = self.object.company_description
        context['company_type_of_application'] = self.object.company_type_of_application.split()

        context['frontend_languages'] = self.object.frontend_languages.split()
        context['frontend_framework'] = self.object.frontend_framework.split()
        context['frontend_libraries'] = self.object.frontend_libraries.split()
        context['frontend_description'] = self.object.frontend_description

        context['backend_languages'] = self.object.frontend_libraries.split()
        context['backend_framework'] = self.object.backend_framework.split()
        context['backend_libraries'] = self.object.backend_libraries.split()
        context['backend_description'] = self.object.backend_description

        context['database'] = self.object.database.split()
        context['database_description'] = self.object.database_description

        context['server_os'] = self.object.server_os
        context['server_configuration'] = self.object.server_configuration
        context['server_ram'] = self.object.server_ram
        context['server_nodes'] = self.object.server_nodes
        context['server_hosting_provider'] = self.object.server_hosting_provider
        context['server_description'] = self.object.server_description

        return context

@login_required
def CreateStackForm(request):
    if request.method == 'POST':
        form = TechStackForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('company_page', args=[form.instance.company_slug]))
    else:
        form = TechStackForm() # An unbound form

    return render_to_response('create-stack.html',{'form': form,} ,context_instance=RequestContext(request))


class SearchListView(ListView):
	model=TechStack
	context_object_name = 'object_list'
	template_name = 'search_results.html'

	def get_queryset(self):
		queryset=[]
		try:
			from itertools import chain
			tag = self.request.GET['q']
			q1 = TechStack.objects.filter(frontend_languages__icontains=tag).order_by('-id')
			q2 = TechStack.objects.filter(company_name__icontains=tag).order_by('-id')
			q3 = TechStack.objects.filter(frontend_framework__icontains=tag).order_by('-id')
			q4 = TechStack.objects.filter(frontend_libraries__icontains=tag).order_by('-id')
			q5 = TechStack.objects.filter(backend_languages__icontains=tag).order_by('-id')
			q6 = TechStack.objects.filter(backend_framework__icontains=tag).order_by('-id')
			q7 = TechStack.objects.filter(database__icontains=tag).order_by('-id')
			q8 = TechStack.objects.filter(server_os__icontains=tag).order_by('-id')
			q9 = TechStack.objects.filter(server_hosting_provider__icontains=tag).order_by('-id')
			queryset=chain(q1,q2,q3,q4,q5,q6,q7,q8,q9)
		except:
			pass
		return queryset

	def get_context_data(self, **kwargs):
		context = super(SearchListView, self).get_context_data(**kwargs)
		try:
			context['search_term'] = self.request.GET['q']
		except:
			context['search_term'] = 'nothing'
 		return context

stack/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>
            Techstack | What's your stack?
        </title>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description">
        <meta name="author">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" type="text/javascript"></script>
        <style type="text/css">
        body {
                                padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
                        }
        </style>
        <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/css/bootstrap-combined.min.css" rel="stylesheet" type="text/css">
        {% load staticfiles %}
        <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'assets/ico/apple-touch-icon-144-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{STATIC_URL}}assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{STATIC_URL}}assets/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="{{STATIC_URL}}assets/ico/apple-touch-icon-57-precomposed.png">
        <link rel="shortcut icon" href="{{STATIC_URL}}assets/ico/favicon.png">
        <style type="text/css">

        </style>
        <script src='{% static "js/base.js" %}'></script>
        {% block head %}
        {% endblock %} 
    </head>
    <body class="gray-background body-padding-top">
        <div data-mercury="full" id="mercuryblock" style="overflow: visible;">
            <div class="navbar navbar-fixed-top techstack-nav" data-mercury-navbarclass="techstack-nav">
                <div class="navbar-inner">
                    <div class="container">
                        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                        </button><a class="brand" href="/"><img class='offset1' src='{{STATIC_URL}}/img/logo.png' /></a>
                        <div class="nav-collapse collapse">
                            <ul class="nav">
                                <li class="">
                                    <a style='border-left:1px solid white;border-right:1px solid white;height:27px;' href="{% url new_stack %}" class>Submit your Stack</a>
                                </li>
                                <li></li>
                                <li></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        {% block content %}
        {% endblock %} 
        
<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js" type="text/javascript"></script>    
</body>
</html>

stack/templates/create-stack.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
    <link href="{% static 'css/company.css' %}" rel="stylesheet" type="text/css">
    
    <script type="text/javascript" >
	    $(document).ready(function(){
	        $("#id_email").css('width', '278px');
	        $("#id_first_name").css('width', '278px');
	        $("#id_last_name").css('width', '278px');
	    });
	</script>

    <form method="post" action="">
		{% csrf_token %} 
	    {{ form.non_field_errors }}

	    <div class="row-fluid small-padding-top">
	        <div class="span8 offset2 white-card">
	            <h4>
	                Company
	            </h4>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.company_name.label }}
	            </h6>
	            <div class="">
	                {{ form.company_name.errors }}
	        		{{ form.company_name }}
	            </div>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.company_description.label }}
	            </h6>
	            <div class="">
	                {{ form.company_description.errors }}
	        		{{ form.company_description }}
	            </div>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.company_type_of_application.label }}
	            </h6>
	            <div class="">
	                {{ form.company_type_of_application.errors }}
	        		{{ form.company_type_of_application }}
	            </div>
	        </div>
	    </div>

	    <img class='offset1' style='position:relative;top:100px;left:50px;' src='{{STATIC_URL}}/img/frontEnd.png' />

	    <div class="row-fluid small-padding-top">
	        <div class="span8 offset2 white-card">
	            <h4>
	                Front End
	            </h4>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.frontend_languages.label }}
	            </h6>
	            <div class="">
	                {{ form.frontend_languages.errors }}
	        		{{ form.frontend_languages }}
	            </div>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.frontend_framework.label }}
	            </h6>
	            <div class="">
	                {{ form.frontend_framework.errors }}
	        		{{ form.frontend_framework }}
	            </div>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.frontend_libraries.label }}
	            </h6>
	            <div class="">
	                {{ form.frontend_libraries.errors }}
	        		{{ form.frontend_libraries }}
	            </div>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.frontend_description.label }}
	            </h6>
	            <div class="">
	            	{{ form.frontend_description.errors }}
	        		{{ form.frontend_description }}
	            </div>
	        </div>
	    </div>

	    <img class='offset1' style='position:relative;top:100px;left:50px;' src='{{STATIC_URL}}/img/backEnd.png' />

	    <div class="row-fluid small-padding-top">
	        <div class="span8 offset2 white-card">
	            <h4>
	                Back End
	            </h4>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.backend_languages.label }}
	            </h6>
	            <div class="">
	                {{ form.backend_languages.errors }}
	        		{{ form.backend_languages }}
	            </div>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.backend_framework.label }}
	            </h6>
	            <div class="">
	                {{ form.backend_framework.errors }}
	        		{{ form.backend_framework }}
	            </div>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.backend_libraries.label }}
	            </h6>
	            <div class="">
	                {{ form.backend_libraries.errors }}
	        		{{ form.backend_libraries }}
	            </div>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.backend_description.label }}
	            </h6>
	            <div class="">
	            	{{ form.backend_description.errors }}
	        		{{ form.backend_description }}
	            </div>
	        </div>
	    </div>


	    <img class='offset1' style='position:relative;top:100px;left:50px;' src='{{STATIC_URL}}/img/databases.png' />


	   	<div class="row-fluid small-padding-top">
	        <div class="span8 offset2 white-card">
	            <h4>
	                Databases
	            </h4>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.database.label }}
	            </h6>
	            <div class="">
	                {{ form.database.errors }}
	        		{{ form.database }}
	            </div>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.database_description.label }}
	            </h6>
	            <div class="">
	                {{ form.database_description.errors }}
	        		{{ form.database_description }}
	            </div>
	        </div>
	    </div>

	    <img class='offset1' style='position:relative;top:100px;left:50px;' src='{{STATIC_URL}}/img/server.png' />


	    <div class="row-fluid small-padding-top">
	        <div class="span8 offset2 white-card">
	            <h4>
	                Server
	            </h4>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.server_os.label }}
	            </h6>
	            <div class="">
	                {{ form.server_os.errors }}
	        		{{ form.server_os }}
	            </div>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.server_configuration.label }}
	            </h6>
	            <div class="">
	                {{ form.server_configuration.errors }}
	        		{{ form.server_configuration }}
	            </div>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.server_ram.label }}
	            </h6>
	            <div class="">
	                {{ form.server_ram.errors }}
	        		{{ form.server_ram }}
	            </div>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.server_nodes.label }}
	            </h6>
	            <div class="">
	            	{{ form.server_nodes.errors }}
	        		{{ form.server_nodes }}
	            </div>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.server_hosting_provider.label }}
	            </h6>
	            <div class="">
	            	{{ form.server_hosting_provider.errors }}
	        		{{ form.server_hosting_provider }}
	            </div>
	        </div>
	    </div>
	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	            <h6 class="span3">
	                {{ form.server_description.label }}
	            </h6>
	            <div class="">
	            	{{ form.server_description.errors }}
	        		{{ form.server_description }}
	            </div>
	        </div>
	    </div>

	    <div class="row-fluid">
	        <div class="span8 offset2 white-card fieldWrapper">
	        	<p><input type="submit" value="Submit your Stack!" class="btn btn-danger" /></p>
	        </div>
	    </div>

	    
	</form>




{% endblock %}

stack/templates/search_results.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
    <link href="{% static 'css/company.css' %}" rel="stylesheet" type="text/css">
    
    <div class="span6 offset5 small-padding-top">
        <h2>Search results for {{ search_term|capfirst }}...</h2>
    </div>

    {% ifnotequal object_list|length 0 %}
    {% for stack in object_list %}
    <div class="row-fluid small-padding-top">
        <div class="span8 offset2 white-card">
            <a href='/company/{{stack.get_company_slug}}'>
                <h1>
                {{stack.get_domain}}
                </h1>
            </a>
            {% for tag in stack.get_summary_tags %}
            <div class="stack-tag">
                {{tag}}
            </div>
            {% endfor %}

            <p class="light-text small-padding-top">
                {{stack.get_company_description}}
            </p>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span8 offset2 gray-card">
            <p class="light-text">
                Submitted by {% for c in stack.get_contributors %}<b>{{c}}</b> {% endfor %}  
            </p>
        </div>
    </div>
    {% endfor %}
    {% endifnotequal %}


{% endblock %}